apiVersion: v1
kind: Namespace
metadata:
  name: pet
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
  labels:
    app: database
  name: database
  namespace: pet
spec:
  replicas: 1
  selector:
    matchLabels:
      app: database
  template:
    metadata:
      labels:
        app: database
    spec:
      containers:
      - image: registry.local-clu01/mydb
        imagePullPolicy: Never
        name: mydb
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: database
  name: database
  namespace: pet
spec:
  ports:
  - port: 5432
    protocol: TCP
    targetPort: 5432
  selector:
    app: database
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
  labels:
    app: api
  name: api
  namespace: pet
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
      - image: registry.local-clu01/myapi
        imagePullPolicy: Always
        name: myapi
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: api
  name: api
  namespace: pet
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: api
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
  labels:
    app: ui
  name: ui
  namespace: pet
spec:
  replicas: 3
  selector:
    matchLabels:
      app: ui
  template:
    metadata:
      labels:
        app: ui
    spec:
      containers:
      - image: registry.local-clu01/myui:20250422
        imagePullPolicy: Always
        name: myui
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: ui
  name: ui
  namespace: pet
spec:
  ports:
  - port: 3000
    protocol: TCP
    targetPort: 3000
  selector:
    app: ui
  type: ClusterIP
  #type: LoadBalancer
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: pet
  namespace: pet
  #annotations:
  #  nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  #ingressClassName: "nginx"
  rules:
  - host: pet.local-clu01
    http:
      paths:
      - backend:
          service:
            name: ui
            port:
              number: 3000
        path: /pet
        pathType: Exact


